from datetime import datetime, timedelta, timezone

from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from app import models
from app.api.deps import get_db
from app.core.state import app_state

router = APIRouter(prefix="/scheduler", tags=["Workflows"])


@router.post("/run-recurring-billing")
def run_recurring_billing_scheduler(db: Session = Depends(get_db)):
    today = datetime.now(timezone.utc)
    plans = db.query(models.RecurringBilling).filter(
        models.RecurringBilling.is_active == True,
        models.RecurringBilling.next_billing_date <= today,
    ).all()
    created_invoices = []
    for plan in plans:
        invoice_number = f"AUTO-{plan.id}-{int(datetime.now().timestamp())}"
        new_invoice = models.Invoice(
            invoice_number=invoice_number,
            customer_id=plan.customer_id,
            user_id=plan.user_id,
            due_date=plan.next_billing_date,
            status="draft",
            total_amount=plan.amount,
            notes=f"Auto-generated by scheduler from plan: {plan.title}",
        )
        db.add(new_invoice)
        db.flush()
        if plan.frequency == "monthly":
            plan.next_billing_date += timedelta(days=30)
        elif plan.frequency == "quarterly":
            plan.next_billing_date += timedelta(days=90)
        elif plan.frequency == "yearly":
            plan.next_billing_date += timedelta(days=365)
        created_invoices.append(new_invoice.invoice_number)
    db.commit()
    app_state.record_workflow()
    return {
        "message": "Recurring billing scheduler completed",
        "created_invoices": created_invoices,
        "count": len(created_invoices),
    }
