"""full initial schema

Revision ID: 42d6a3590e31
Revises: 46ce8e874851
Create Date: 2026-05-23 22:17:45.183856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42d6a3590e31'
down_revision: Union[str, Sequence[str], None] = '46ce8e874851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invoices_customer_id_fkey', 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_clients_team'), table_name='clients')
    op.drop_column('clients', 'notes')
    op.drop_column('clients', 'total_revenue')
    op.drop_column('clients', 'payment_terms')
    op.alter_column('invoice_items', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('invoice_items', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
    op.alter_column('invoice_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('invoice_items', 'total_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('invoice_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoice_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_foreign_key(op.f('fk_invoice_items_invoice_id_invoices'), 'invoice_items', 'invoices', ['invoice_id'], ['id'])
    op.drop_column('invoice_items', 'line_total')
    op.drop_column('invoice_items', 'notes')
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('invoices', 'notes',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('invoices', 'subtotal',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('invoices', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_invoices_client'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_team'), table_name='invoices')
    op.create_index(op.f('ix_invoices_client_id'), 'invoices', ['client_id'], unique=False)
    op.create_index(op.f('ix_invoices_due_date'), 'invoices', ['due_date'], unique=False)
    op.create_index(op.f('ix_invoices_is_deleted'), 'invoices', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_invoices_public_share_token'), 'invoices', ['public_share_token'], unique=True)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index('ix_invoices_status_due', 'invoices', ['status', 'due_date'], unique=False)
    op.create_index('ix_invoices_team_due', 'invoices', ['team_id', 'due_date'], unique=False)
    op.create_index(op.f('ix_invoices_team_id'), 'invoices', ['team_id'], unique=False)
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    op.create_index('ix_invoices_user_status', 'invoices', ['user_id', 'status'], unique=False)
    op.create_foreign_key(op.f('fk_invoices_user_id_users'), 'invoices', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_invoices_workflow_id_workflows'), 'invoices', 'workflows', ['workflow_id'], ['id'])
    op.drop_column('invoices', 'payment_method')
    op.drop_column('invoices', 'paid_amount')
    op.drop_column('invoices', 'viewed_at')
    op.drop_column('invoices', 'customer_id')
    op.drop_column('invoices', 'ai_priority_score')
    op.drop_column('invoices', 'payment_reference')
    op.drop_column('invoices', 'last_reminder_at')
    op.drop_column('invoices', 'reminder_count')
    op.drop_column('invoices', 'paid_at')
    op.drop_column('invoices', 'sent_at')
    op.add_column('recurring_billings', sa.Column('client_id', sa.Integer(), nullable=False))
    op.add_column('recurring_billings', sa.Column('team_id', sa.Integer(), nullable=True))
    op.add_column('recurring_billings', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('recurring_billings', sa.Column('currency', sa.String(length=10), nullable=True))
    op.add_column('recurring_billings', sa.Column('last_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('recurring_billings', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('recurring_billings', sa.Column('auto_send', sa.Boolean(), nullable=True))
    op.add_column('recurring_billings', sa.Column('dynamic_amount_enabled', sa.Boolean(), nullable=True))
    op.add_column('recurring_billings', sa.Column('failure_count', sa.Integer(), nullable=True))
    op.add_column('recurring_billings', sa.Column('last_failure_reason', sa.String(length=300), nullable=True))
    op.add_column('recurring_billings', sa.Column('total_generated', sa.Integer(), nullable=True))
    op.add_column('recurring_billings', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('recurring_billings', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('recurring_billings', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('recurring_billings', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('recurring_billings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('recurring_billings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_recurring_billings_client_id'), 'recurring_billings', ['client_id'], unique=False)
    op.create_index(op.f('ix_recurring_billings_is_deleted'), 'recurring_billings', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_recurring_billings_next_billing_date'), 'recurring_billings', ['next_billing_date'], unique=False)
    op.create_index(op.f('ix_recurring_billings_user_id'), 'recurring_billings', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_recurring_billings_team_id_teams'), 'recurring_billings', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(op.f('fk_recurring_billings_user_id_users'), 'recurring_billings', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_recurring_billings_client_id_clients'), 'recurring_billings', 'clients', ['client_id'], ['id'])
    op.drop_column('recurring_billings', 'customer_id')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'ai_usage_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'ai_tokens_consumed',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.execute("UPDATE users SET updated_at = NOW() WHERE updated_at IS NULL")
    op.execute("UPDATE users SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE invoices SET updated_at = NOW() WHERE updated_at IS NULL")
    op.execute("UPDATE invoices SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE invoice_items SET updated_at = NOW() WHERE updated_at IS NULL")
    op.execute("UPDATE invoice_items SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE recurring_billings SET updated_at = NOW() WHERE updated_at IS NULL")
    op.execute("UPDATE recurring_billings SET created_at = NOW() WHERE created_at IS NULL")
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_team_id'), 'users', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_team_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.alter_column('users', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'ai_tokens_consumed',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'ai_usage_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('recurring_billings', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_recurring_billings_client_id_clients'), 'recurring_billings', type_='foreignkey')
    op.drop_constraint(op.f('fk_recurring_billings_user_id_users'), 'recurring_billings', type_='foreignkey')
    op.drop_constraint(op.f('fk_recurring_billings_team_id_teams'), 'recurring_billings', type_='foreignkey')
    op.drop_index(op.f('ix_recurring_billings_user_id'), table_name='recurring_billings')
    op.drop_index(op.f('ix_recurring_billings_next_billing_date'), table_name='recurring_billings')
    op.drop_index(op.f('ix_recurring_billings_is_deleted'), table_name='recurring_billings')
    op.drop_index(op.f('ix_recurring_billings_client_id'), table_name='recurring_billings')
    op.alter_column('recurring_billings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('recurring_billings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('recurring_billings', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('recurring_billings', 'amount',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('recurring_billings', 'deleted_at')
    op.drop_column('recurring_billings', 'is_deleted')
    op.drop_column('recurring_billings', 'total_generated')
    op.drop_column('recurring_billings', 'last_failure_reason')
    op.drop_column('recurring_billings', 'failure_count')
    op.drop_column('recurring_billings', 'dynamic_amount_enabled')
    op.drop_column('recurring_billings', 'auto_send')
    op.drop_column('recurring_billings', 'end_date')
    op.drop_column('recurring_billings', 'last_generated_at')
    op.drop_column('recurring_billings', 'currency')
    op.drop_column('recurring_billings', 'description')
    op.drop_column('recurring_billings', 'team_id')
    op.drop_column('recurring_billings', 'client_id')
    op.add_column('invoices', sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('reminder_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('last_reminder_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('payment_reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('ai_priority_score', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('viewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('paid_amount', sa.NUMERIC(precision=14, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_invoices_workflow_id_workflows'), 'invoices', type_='foreignkey')
    op.drop_constraint(op.f('fk_invoices_user_id_users'), 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_customer_id_fkey'), 'invoices', 'customers', ['customer_id'], ['id'])
    op.drop_index('ix_invoices_user_status', table_name='invoices')
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_team_id'), table_name='invoices')
    op.drop_index('ix_invoices_team_due', table_name='invoices')
    op.drop_index('ix_invoices_status_due', table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_public_share_token'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_is_deleted'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_due_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_client_id'), table_name='invoices')
    op.create_index(op.f('ix_invoices_team'), 'invoices', ['team_id'], unique=False)
    op.create_index(op.f('ix_invoices_client'), 'invoices', ['client_id'], unique=False)
    op.alter_column('invoices', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('invoices', 'subtotal',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('invoices', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('invoice_items', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('invoice_items', sa.Column('line_total', sa.NUMERIC(precision=14, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_invoice_items_invoice_id_invoices'), 'invoice_items', type_='foreignkey')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.alter_column('invoice_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoice_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoice_items', 'total_price',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('invoice_items', 'unit_price',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('invoice_items', 'quantity',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('invoice_items', 'description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('clients', sa.Column('payment_terms', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('total_revenue', sa.NUMERIC(precision=14, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_clients_team'), 'clients', ['team_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('customers_pkey'))
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    # ### end Alembic commands ###
